/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_ugv_robot_1.glb --shadows 
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce
Title: McLaren F1 1993 By Alex.Ka.🤍🖤
*/

import * as THREE from 'three'
import { useLayoutEffect, useRef } from 'react'
import { useGLTF, CubeCamera } from '@react-three/drei'

export default function Model({ carColor, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ejemplo.glb')

  useLayoutEffect(() => {
    // Body materials
    materials.McLaren_F1_1993_By_Alex_Ka.color.set(carColor)
    materials.McLaren_F1_1993_By_Alex_Ka.metalness = 0.4
    materials.McLaren_F1_1993_By_Alex_Ka.roughness = 0.0
    materials.McLaren_F1_1993_By_Alex_Ka.clearcoat = 1
    materials.McLaren_F1_1993_By_Alex_Ka.envMapIntensity = 1

    // Chrome parts
    materials.chrome.metalness = 1
    materials.chrome.roughness = 0.1
    materials.chrome.envMapIntensity = 1.5

    materials.chrome2.metalness = 1
    materials.chrome2.roughness = 0.1
    materials.chrome2.envMapIntensity = 1.5

    // Windows
    materials.windo_F.transparent = true
    materials.windo_F.opacity = 0.6
    materials.windo_F.color = new THREE.Color('white')
    materials.windo_F.roughness = 0.0
    materials.windo_F.metalness = 1.0
    materials.windo_F.needsUpdate = true
    
    materials.windo_R.transparent = true
    materials.windo_R.opacity = 0.6
    materials.windo_R.color = new THREE.Color('white')
    materials.windo_R.needsUpdate = true
    
    materials.windo_S.transparent = true
    materials.windo_S.opacity = 0.6
    materials.windo_S.color = new THREE.Color('white')
    materials.windo_S.needsUpdate = true

    // Lights
    materials.headlight_1.emissiveIntensity = 1000
    materials.headlight_2.emissiveIntensity = 100
    materials.rear_lamp.emissiveIntensity = 100000
    materials.brakelight.emissiveIntensity = 10000

    // Tires
    materials.tire.roughness = 0.9
    materials.tire.metalness = 0
    materials.tire.color.set('black')

    // Enhance all materials
    Object.values(materials).forEach((material) => {
      if (!material.emissive) {
        material.envMapIntensity = material.envMapIntensity || 1
      }
    })
  }, [materials, carColor]) 

  return (
    <group ref={group} {...props} dispose={null}>
      <CubeCamera frames={1} position={[0, 1.5, 0]} near={0.1} resolution={512}>
        {(texture) => (
          <group position={[0, -1.5, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={1.075}>
              <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.F1_front_plastic} />
              <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.F1_nip_logo} />
              <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.F1_red_F} />
              <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.F1_red_R} />
              <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.F1_side} />
              <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.McLAREN_RED_LINE} />
              <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.McLAREN_sidelogo} />
              <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.McLAREN_sidelogo_FBUMPER} />
              <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.McLaren_F1_1993_By_Alex_Ka} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.McLaren_logo} />
              <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.McLaren_supportlogo} />
              <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.material} />
              <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.black_aluminium} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.black_chrome} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.black_chrome2} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.black_matte} />
              <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.black_plastic} />
              <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.bottom} />
              <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.brakedisk} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.brakelight} />
              <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.bronze} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.chrome} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.chrome2} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.door_stitch} />
              <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.engine} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.exhaust} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.exhaust_gold} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials.exhaust_hole} />
              <mesh castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials.exhaust_metal_circles} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials.exhaust_hole} />
              <mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials.floor} />
              <mesh castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials.fuel_clap} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.grill1} />
              <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.grill2} />
              <mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={materials.grill_3} />
              <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.grill_f} />
              <mesh castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials.grill_side} />
              <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials.headlight_1} />
              <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials.headlight_2} />
              <mesh castShadow receiveShadow geometry={nodes.Object_41.geometry} material={materials.headlightglass} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials.interior} />
              <mesh castShadow receiveShadow geometry={nodes.Object_43.geometry} material={materials.mirrors} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials.material_42} />
              <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials.material_43} />
              <mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials.plate_F} />
              <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.plate_R} />
              <mesh castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials.rear_lamp} />
              <mesh castShadow receiveShadow geometry={nodes.Object_49.geometry} material={materials.rear_turn_signal} />
              <mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials.material_48} />
              <mesh castShadow receiveShadow geometry={nodes.Object_51.geometry} material={materials.rimbolt} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials.rimlogo} />
              <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials.side_turn_signal} />
              <mesh castShadow receiveShadow geometry={nodes.Object_54.geometry} material={materials.suport} />
              <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.tire} />
              <mesh castShadow receiveShadow geometry={nodes.Object_56.geometry} material={materials.tire_side} />
              <mesh castShadow receiveShadow geometry={nodes.Object_57.geometry} material={materials.windo_F} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_58.geometry} material={materials.windo_R} material-envMap={texture} />
              <mesh castShadow receiveShadow geometry={nodes.Object_59.geometry} material={materials.windo_S} material-envMap={texture} />
            </group>
          </group>
        )}
      </CubeCamera>
    </group>
  )
}

useGLTF.preload('/ejemplo.glb')