/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sample.glb --transform 
Files: sample.glb [1.16MB] > C:\Users\inaki\Escritorio\html_modelviewer\gltfjsx-master\sample-transformed.glb [1.13MB] (2%)
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce
Title: McLaren F1 1993 By Alex.Ka.🤍🖤
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sample.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.348, 0.011, 5.412]} rotation={[Math.PI / 2, 0, 0]} scale={0.697}>
        <mesh geometry={nodes.欧式儿童小孩人物_1.geometry} material={materials.A_11_39} />
        <mesh geometry={nodes.欧式儿童小孩人物_2.geometry} material={materials.A11_03} />
        <mesh geometry={nodes.欧式儿童小孩人物_3.geometry} material={materials.A_11_69} />
      </group>
      <mesh geometry={nodes.Yellow_Carpet.geometry} material={materials.RubberAmarilloPileta} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Side_Yellow.geometry} material={materials.RubberAmarilloAleron} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Yellow_Fabric_Top.geometry} material={materials.RubberAmarilloToldo} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Tela_Amarilla.geometry} material={materials['Yellow leather']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Tela_Amarilla001.geometry} material={materials['Yellow leather']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Tela_Negra.geometry} material={materials['Black fabric']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Tela_Negra001.geometry} material={materials['Black fabric']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Tela_Roja.geometry} material={materials['Car leather red']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Tela_Blanca.geometry} material={materials['White leather']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Tela_Blanca001.geometry} material={materials['White leather']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Red_Body.geometry} material={materials['Red Inflatable Main']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Staircase.geometry} material={materials['Scratched Glossy Red Plastic']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Landing_Zone.geometry} material={materials['Scratched Glossy Red Plastic.001']} position={[4.599, 0.149, -0.128]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sides_Black.geometry} material={materials['Procedural rubber latex']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.wheels.geometry} material={materials.ProceduralrubberlatexRueda} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Stitches.geometry} material={materials['Plain White Sheer']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Stitches001.geometry} material={materials['Plain White Sheer']} position={[0.461, 0.042, 0.676]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Procedual Water with Caustics']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Flamingo_Swim_Ring.geometry} material={materials['Material.003']} position={[-3.61, -3.985, 5.124]} />
      <mesh geometry={nodes.Inflatable_swimming_ring.geometry} material={materials['Translucent Plastic']} position={[-3.61, -3.985, 5.124]} />
      <group position={[5.663, 0.517, -1.151]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.205, 0.205, 0.205]}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials.blue} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials.white} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials.red} />
        <mesh geometry={nodes.Sphere002_3.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Sphere002_4.geometry} material={materials.grey} />
      </group>
      <mesh geometry={nodes.colorful_plastic_balls.geometry} material={materials['colorful plastic balls']} position={[4.927, -0.328, -0.158]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.117} />
    </group>
  )
}


useGLTF.preload('/sample.glb')

// Add default export
export default Model
